### ISSUE TITLE
サイバー感の追加

### ISSUE THREAD

**Issue by danmaid** [danmaid/danmaid.com#4]
以前に作成していたものをもってくる

**Comment by danmaid** [comment]
とりあえずお手軽なこれ。
https://danmaid.github.io/

![image](https://github.com/danmaid/danmaid.com/assets/26823682/747233dd-870b-4226-b4b1-d4afb1e0e289)

**Comment by danmaid** [comment]
```css
      :root {
        --color-fg: #b6c0e2;
        --color-fg-blur: #4762b8;
      }
      :link {
        color: var(--color-fg);
      }
      :visited {
        color: var(--color-fg);
      }
      body {
        background-color: #1a1a1a;
        color: var(--color-fg);
        filter: drop-shadow(0 1px 1px var(--color-fg-blur))
          drop-shadow(1px 0 1px var(--color-fg-blur))
          drop-shadow(0 -1px 1px var(--color-fg-blur))
          drop-shadow(-1px 0 1px var(--color-fg-blur));
      }
      ul > * {
        display: list-item;
      }
```

![image](https://github.com/danmaid/danmaid.com/assets/26823682/82f26c26-788b-4779-aa4d-35c4f72d5605)
